### ISSUE TITLE
Cluster SQL Activity CPU Overhead

### ISSUE THREAD

**Issue by Otterpohl** [cockroachlabs/visus#68]
Enabling the [Cluster SQL Activity Query](https://github.com/cockroachlabs/visus/blob/main/examples/cluster_sqlactivity.yaml) incurs a very large CPU overhead on the CockroachDB cluster, this may not be the case for others.

We tested this on 7 node CockroachDB cluster (Virtual Machines) running on `v22.1.20` where each node has 4 cpu's.

Here you can see the CPU increase from a mean of `7.5%` to a mean of `49%` then back down to the original mean.
![image](https://github.com/cockroachlabs/visus/assets/82106086/3ea8b187-07e6-4e14-ae9b-3cd8728a9dc8)

You can also see massive network egress which i think is due to a default interval of 10 seconds but the query executes for 16 seconds.
![image](https://github.com/cockroachlabs/visus/assets/82106086/2c27799b-4083-441e-8b36-2a6367decd60)

This example should either be improved, or removed from the examples as it sets a bad precedent. The rest of the queries incur a very small overhead.

**Comment by sravotto** [comment]
@Otterpohl - this query is meant to be executed at a cluster level, and very low frequency. It does have a significant overhead otherwise.
If `visus` is deployed in a self hosted cluster as a sidecar for each node, [sql activity](https://github.com/cockroachlabs/visus/blob/main/examples/sqlactivity.yaml) should be used instead.
I'll add a comment and change the scope to make this clear.
